### ISSUE TITLE
input file name in call_stats2surf

### ISSUE THREAD

**Issue by hlesaint** [gjheij/linescanning#10]
"nii.gz" is by default part of the `find`-command, so if you input a file with nii.gz at the end it will look for a file with nii.gz.nii.gz

could be fixed via sed 's,.nii.gz.nii.gz,.nii.gz,' or if loop

**Comment by gjheij** [comment]
I can also set `-i` directly to a file, so that the whole `-i` + `-a` combination for a single file is avoided

**Comment by hlesaint** [comment]
would be most straight forward
