### ISSUE TITLE
different affines for spm and fsl masks - module 04

### ISSUE THREAD

**Issue by iverissimo** [gjheij/linescanning#11]
Hi,

When running module 4 on the MP2RAGE of one of my participants I get the following error

```
Combining SPM & FSL mask to include cerebellum too
Traceback (most recent call last):
  File "/Users/verissimo/linescanning/bin/call_mp2rage", line 274, in <module>
    main(sys.argv[1:])
  File "/Users/verissimo/linescanning/bin/call_mp2rage", line 258, in main
    new_mask = image.math_img('(spm + fsl) > 0', spm=brainmask, fsl=opj(inputdir, 'tmp_mask.nii.gz'))
  File "/Users/verissimo/.local/lib/python3.7/site-packages/nilearn/image/image.py", line 907, in math_img
    _check_same_fov(*niimgs, raise_error=True)
  File "/Users/verissimo/.local/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py", line 67, in _check_same_fov
    for e in errors]))
ValueError: ("Input images cannot be compared, you provided 'dict_values(['/Volumes/Verissimo_Seagate_Hub_Plus/Projects/FAM/DATA/anat_preprocessing/derivatives/pymp2rage/sub-011/ses-1/sub-011_ses-1_acq-MP2RAGE_desc-spm_mask.nii.gz', '/Volumes/Verissimo_Seagate_Hub_Plus/Projects/FAM/DATA/anat_preprocessing/sub-011/ses-1/tmp_mask.nii.gz'])',", 'Following field of view errors were detected:\n- img_#0 and img_#1 do not have the same affine')
```

When checking, indeed their affine is slighty different (probably due to some rounding error)
**img_1.affine**
```
array([[ 6.99586272e-01, -2.39259005e-02,  0.00000000e+00,
        -8.79358139e+01],
       [ 2.40633488e-02,  6.95588470e-01,  4.85897064e-04,
        -1.21713348e+02],
       [-1.68085098e-05, -4.85658646e-04,  6.95999801e-01,
        -1.34004532e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])
```
**img_2affine**
```
array([[ 6.99586272e-01, -2.39258446e-02,  0.00000000e+00,
        -8.79358139e+01],
       [ 2.40633450e-02,  6.95588470e-01,  4.85899596e-04,
        -1.21713348e+02],
       [-1.67993858e-05, -4.85612400e-04,  6.95999801e-01,
        -1.34004532e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])
```

I didn't have this before, so am wondering why this only happened now... And which of the affines is the one that should be used throughout the pipeline?

**Comment by gjheij** [comment]
Ugh, this is always an annoying one. What's the affine of the input imag; i.e., the `T1w`-image from pymp2rage. That should be the leading one. If the masks are aligned properly with this T1w-image, you can use `fslcpgeom <souce> <destination>` to enforce the same affine. 

Shouldn't happen, though, unless one mask already existed stemming from a slightly different image. Did you try to remove both masks and re-run it?

**Comment by iverissimo** [comment]
Hey, left this hanging and now came back to it.

This happened in **module 04** - so after creating the T1w uni image, when combining the FSL and SPM masks. The mask produced by SPM had a slightly different affine than the one produced by FSL's bet2 (which was exactly the same one as the inv2 mag image).

My solution was to use `fslcpgeom <tmp_mask.nii.gz> <spm_mask.nii.gz>` which lead them to have the same affine. After that I ran `image.math_img('(spm + fsl) > 0')`, removed the T1w file from the pymp2rage folder and then could re-run module 04 without issue.

I just find it weird that this happened with only my last participant, and can't figure out why this rounding diff... I'm now running the rest of the anat pipeline, hoping that there's no more hiccups
