### ISSUE TITLE
eyetrack reading TR/vols

### ISSUE THREAD

**Issue by marcoaqil** [gjheij/linescanning#16]
unclear what to set as TR/vols for self-paced experiment out of the scanner and what the parameters do

**Comment by gjheij** [comment]
If `nr_vols` and `TR` are kept None, it'll read to the end of the eyetracker file. The [example call here](https://linescanning.readthedocs.io/en/latest/examples/eyetracker.html) then becomes:
```python
eye_ = dataset.ParseEyetrackerFile(
    edf_file,
    use_bids=False,
    verbose=True
)
```

This behavior is default now. I also updated the docs to include `fMRI` next to `nr_vols` and `TR`, denoting that you can use these for fMRI experiments. However, also for those experiments the end of the file can be used as end point. Up to the user:)
