### ISSUE TITLE
Usage of pipeline requires bash>4.0

### ISSUE THREAD

**Issue by gjheij** [gjheij/linescanning#3]
Some pieces of code will fail if the bash version is below 4.0. Could be made more explicit by specifying `bash` in front of the `spinoza_*` modules in the master script.

Could also add a check for bash version in `spinoza_setup` during installation. Update docs too.

**Comment by iverissimo** [comment]
To add to this, would be better to specify that one needs bash and not zshell.
Indeed, even in a bash terminal, code works without issue if specifying `bash spinoza_*` in the master script in each module. 
Also needed to add `bash call_cat12` within spinoza_brainextraction

**Comment by gjheij** [comment]
Added a version check  [here](https://github.com/gjheij/linescanning/blob/main/shell/master#L9) and changed the shebang line [here](https://github.com/gjheij/linescanning/blob/main/bin/call_cat12#L1) to look for the environmental executable of `bash`. Maybe that works in the same way as `bash call_cat12`. If so, I can adapt that globally.

**Comment by iverissimo** [comment]
Version check in master script works, but needed to replace the shebang line `#!/bin/sh ` with
`#!/usr/local/bin/bash `
With the previous line, the bash version echoed by `$BASH_VERSINFO `was different from the one in the terminal I'm running from.

**Comment by gjheij** [comment]
Understandable. Can you check with `#!/usr/bin/env bash`?

**Comment by iverissimo** [comment]
Also works!

**Comment by gjheij** [comment]
Excellent, will change it to that

**Comment by gjheij** [comment]
Is `$BASH_VERSION` accurate in that case?

**Comment by iverissimo** [comment]
> Is `$BASH_VERSION` accurate in that case?

yep, `$BASH_VERSION `is accurate (`5.1.16(1)-release`) and `$BASH_VERSINFO` echoes the same version (`5`)

**Comment by gjheij** [comment]
Brilliant, thanks for verifying!
