### ISSUE TITLE
matlab alias fix in call_bashhelper

### ISSUE THREAD

**Issue by iverissimo** [gjheij/linescanning#4]
When calling matlab, current code assumes that there is an alias command `matlab`.
Because I switched from zshell to bash, alias are not inherited and calling `matlab` would return command not found error message.
My fix for this was to replace it with `$MATLAB_DIR`:
`$MATLAB_DIR -nosplash -nodisplay -batch "addpath('$(dirname ${1})'); $(basename ${1} .m)" | tail -n +${skip_lines} # suppress intro text`
This worked, not sure if best fix

**Comment by gjheij** [comment]
I definitely noticed that the matlab-command seems to vary across systems; not just the path to matlab, but also how to initiate it from the terminal (the `-batch "addpath(...)"` stuff). Need to add some instructions on how to invoke matlab from the terminal across different platforms
