### ISSUE TITLE
missing warp-files for call_antsapplytransforms

### ISSUE THREAD

**Issue by iverissimo** [gjheij/linescanning#8]
When running `spinoza_sinusfrommni` got the `missing file` error even though the files are in the the ants folder. 
Noticed that lines `172` and `173` expected  MNI152Nlin6Asym and files created in module 5 are called MNI152N**L**in6Asym (so capital letter). I guess it's related to the version of ANTs used, but have not checked to be sure

**Comment by gjheij** [comment]
Oh, that's purely a typo I guess. Good catch👍
